// src/lib/mockData.ts - Realistic seed data for Partner.ai
import {
  User,
  GbpAccount,
  GbpPost,
  GbpReview,
  AiReplyConfig,
  GbpPhoto,
  PricingPlan,
  KpiSummary,
  AgencyTeamMember,
  GlobalPlatformSettings
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'user-single',
    name: 'Elena Rostova',
    email: 'elena@artisanroast.com',
    role: 'single',
    planId: 'plan-single',
    companyName: 'Artisan Roast & Espresso',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'user-agency',
    name: 'Marcus Vance',
    email: 'marcus@peakscalemedia.com',
    role: 'agency',
    planId: 'plan-agency-pro',
    companyName: 'PeakScale Growth Agency',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    createdAt: '2023-11-10T10:30:00Z',
  },
  {
    id: 'user-admin',
    name: 'Alex Chen',
    email: 'alex@partner.ai',
    role: 'super_admin',
    planId: 'plan-enterprise',
    companyName: 'Partner.ai Core Team',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    createdAt: '2023-01-01T00:00:00Z',
  }
];

export const INITIAL_GBP_ACCOUNTS: GbpAccount[] = [
  // Single user account
  {
    id: 'gbp-artisan',
    ownerUserId: 'user-single',
    locationName: 'Artisan Roast & Bakery - Hayes Valley',
    clientLabel: 'Artisan Roast Hayes Valley',
    googleAccountId: 'accounts/1094829104819/locations/7749201',
    address: '428 Hayes St, San Francisco, CA 94102',
    phone: '(415) 555-0182',
    category: 'Coffee Shop & Bakery',
    connected: true,
    connectedAt: '2024-01-16T10:00:00Z',
    healthScore: 94,
    rating: 4.8,
    reviewsCount: 342,
  },
  // Agency user accounts (Clients)
  {
    id: 'gbp-blueharbor',
    ownerUserId: 'user-agency',
    clientLabel: 'Blue Harbor Seafood Grille',
    locationName: 'Blue Harbor Seafood Grille - Pier 39',
    googleAccountId: 'accounts/2091837491023/locations/8839201',
    address: 'Beach Street & The Embarcadero, SF, CA',
    phone: '(415) 555-0199',
    category: 'Seafood Restaurant',
    connected: true,
    connectedAt: '2023-11-15T14:20:00Z',
    healthScore: 92,
    rating: 4.7,
    reviewsCount: 812,
  },
  {
    id: 'gbp-summitdental',
    ownerUserId: 'user-agency',
    clientLabel: 'Summit Ridge Dental Practice',
    locationName: 'Summit Ridge Dental Specialists',
    googleAccountId: 'accounts/2091837491023/locations/4491022',
    address: '890 Market St #400, San Francisco, CA',
    phone: '(415) 555-0134',
    category: 'Cosmetic Dentist',
    connected: true,
    connectedAt: '2023-12-01T09:15:00Z',
    healthScore: 88,
    rating: 4.9,
    reviewsCount: 198,
  },
  {
    id: 'gbp-apexfitness',
    ownerUserId: 'user-agency',
    clientLabel: 'Apex Strength & Fitness Club',
    locationName: 'Apex Strength & Conditioning',
    googleAccountId: 'accounts/2091837491023/locations/1209384',
    address: '150 4th Street, San Francisco, CA',
    phone: '(415) 555-0177',
    category: 'Gym & Fitness Center',
    connected: true,
    connectedAt: '2024-01-05T11:00:00Z',
    healthScore: 85,
    rating: 4.6,
    reviewsCount: 264,
  },
  {
    id: 'gbp-bellavita',
    ownerUserId: 'user-agency',
    clientLabel: 'Bella Vita Wood-Fired Trattoria',
    locationName: 'Bella Vita Trattoria North Beach',
    googleAccountId: 'accounts/2091837491023/locations/9948201',
    address: '540 Columbus Ave, San Francisco, CA',
    phone: '(415) 555-0128',
    category: 'Italian Restaurant',
    connected: true,
    connectedAt: '2024-01-20T16:45:00Z',
    healthScore: 96,
    rating: 4.9,
    reviewsCount: 650,
  },
  {
    id: 'gbp-luxeauto',
    ownerUserId: 'user-agency',
    clientLabel: 'Luxe Precision Auto Spa',
    locationName: 'Luxe Detail & Ceramic Coating',
    googleAccountId: 'accounts/2091837491023/locations/5592810',
    address: '1220 Folsom St, San Francisco, CA',
    phone: '(415) 555-0145',
    category: 'Car Detailing Service',
    connected: true,
    connectedAt: '2024-02-01T13:30:00Z',
    healthScore: 79,
    rating: 4.5,
    reviewsCount: 142,
  },
];

export const INITIAL_AI_CONFIGS: Record<string, AiReplyConfig> = {
  'gbp-artisan': {
    gbpAccountId: 'gbp-artisan',
    persona: `Tone: Warm, artisanal, courteous, passionate about craft coffee and fresh sourdough.
Guidelines:
- Greet the reviewer warmly by name if provided.
- For 4-5 star reviews: Express sincere gratitude, mention our rotating single-origin roasts, and warmly invite them to sample our morning pastries next visit.
- For 1-3 star reviews: Apologize with genuine care for falling short of our standards, do NOT offer excuses, invite them to email elena@artisanroast.com so we can brew them a replacement cup or refund.
- Keep reply under 3-4 sentences.`,
    autoReplyEnabled: true,
    autoReplyMinRating: 4,
    signature: '— Warmly, Elena & the Artisan Roast Barista Team ☕',
    llmProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    apiKeyMasked: 'sk-ant-api03-••••••••••••••••9F4d',
  },
  'gbp-blueharbor': {
    gbpAccountId: 'gbp-blueharbor',
    persona: `Tone: Enthusiastic, hospitable, maritime culinary excellence.
Guidelines:
- Celebrate memorable waterfront dining experiences.
- Highlight fresh daily catch sourced from local Pacific docks.
- For any service delays, offer immediate management contact at reservations@blueharbor.com.`,
    autoReplyEnabled: true,
    autoReplyMinRating: 5,
    signature: '— Chef Mateo & The Pier 39 Crew 🐟',
    llmProvider: 'openai',
    modelName: 'gpt-4o',
    apiKeyMasked: 'sk-proj-••••••••••••••••k9x2',
  },
  'gbp-summitdental': {
    gbpAccountId: 'gbp-summitdental',
    persona: `Tone: Professional, reassuring, gentle, HIPAA-compliant (never mention specific medical treatments).
Guidelines:
- Emphasize patient comfort, pain-free modern dentistry, and welcoming care.
- For concerns, direct to office manager at care@summitdental.com.`,
    autoReplyEnabled: false,
    autoReplyMinRating: 5,
    signature: '— Dr. Aris Thorne & The Summit Ridge Care Staff',
    llmProvider: 'anthropic',
    modelName: 'claude-3-5-sonnet',
    apiKeyMasked: 'sk-ant-api03-••••••••••••••••3L8q',
  },
};

export const INITIAL_POSTS: GbpPost[] = [
  {
    id: 'post-1',
    gbpAccountId: 'gbp-artisan',
    type: 'STANDARD',
    caption: 'Autumn is here! 🍂 Try our brand-new Spiced Cardamom Maple Cortado brewed with oat milk and house-roasted Ethiopian Yirgacheffe beans. Pairs perfectly with our almond croissant fresh from the oven at 7:30 AM.',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    ctaLabel: 'Order Online',
    ctaLink: 'https://artisanroast.com/order',
    status: 'PUBLISHED',
    publishedAt: '2024-03-10T14:30:00Z',
    viewsCount: 1420,
    clicksCount: 89,
  },
  {
    id: 'post-2',
    gbpAccountId: 'gbp-artisan',
    type: 'EVENT',
    caption: 'Join us this Saturday evening for our monthly Latte Art Throwdown & Tasting Flight! Live jazz trio, complimentary single-origin cupping session, and prizes for local baristas.',
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80',
    eventTitle: 'Saturday Live Jazz & Coffee Cupping',
    eventStart: '2024-03-23T18:00:00Z',
    eventEnd: '2024-03-23T21:00:00Z',
    ctaLabel: 'Sign Up',
    ctaLink: 'https://artisanroast.com/events/jazz-cupping',
    status: 'SCHEDULED',
    scheduledAt: '2024-03-20T09:00:00Z',
    viewsCount: 0,
    clicksCount: 0,
  },
  {
    id: 'post-3',
    gbpAccountId: 'gbp-artisan',
    type: 'OFFER',
    caption: 'Neighbourhood Appreciation Week: Enjoy 20% off all whole-bean coffee bags when you show this Google Business offer at checkout.',
    imageUrl: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=800&q=80',
    couponCode: 'HAYES20',
    terms: 'Valid through Sunday at our Hayes St location only. Limit 2 bags per customer.',
    ctaLabel: 'Learn More',
    ctaLink: 'https://artisanroast.com/specials',
    status: 'PUBLISHED',
    publishedAt: '2024-03-01T10:00:00Z',
    viewsCount: 2310,
    clicksCount: 194,
  },
  {
    id: 'post-4',
    gbpAccountId: 'gbp-artisan',
    type: 'PRODUCT',
    caption: 'Ceramic Handcrafted Dripper Set. Custom thrown by local SF ceramicist Maya Lin in matte slate finish. Includes 100 unbleached filters and a 12oz bag of Reserve Geisha.',
    imageUrl: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=800&q=80',
    ctaLabel: 'Buy',
    ctaLink: 'https://artisanroast.com/shop/ceramic-dripper',
    status: 'DRAFT',
    viewsCount: 0,
    clicksCount: 0,
  },
  // Blue Harbor Posts
  {
    id: 'post-5',
    gbpAccountId: 'gbp-blueharbor',
    type: 'STANDARD',
    caption: 'Direct from Dungeness boats this morning: freshly steamed crab with drawn garlic butter and charred sourdough. Sunset table seating now open!',
    imageUrl: 'https://images.unsplash.com/photo-1559742811-822873691df8?auto=format&fit=crop&w=800&q=80',
    ctaLabel: 'Book',
    ctaLink: 'https://blueharbor.com/reserve',
    status: 'PUBLISHED',
    publishedAt: '2024-03-12T16:00:00Z',
    viewsCount: 3840,
    clicksCount: 312,
  },
  {
    id: 'post-6',
    gbpAccountId: 'gbp-bellavita',
    type: 'OFFER',
    caption: 'Truffle Week has arrived in North Beach! Enjoy handmade Tagliolini with shaved black Norcia truffles paired with a glass of Barolo.',
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80',
    ctaLabel: 'Book',
    ctaLink: 'https://bellavita.com/truffle-week',
    status: 'SCHEDULED',
    scheduledAt: '2024-03-25T11:00:00Z',
    viewsCount: 0,
    clicksCount: 0,
  }
];

export const INITIAL_REVIEWS: GbpReview[] = [
  {
    id: 'rev-1',
    gbpAccountId: 'gbp-artisan',
    reviewerName: 'Marcus Sterling',
    reviewerPhotoUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=100&q=80',
    rating: 5,
    text: 'Hands down the most meticulously balanced pour-over in San Francisco. The baristas actually dial in each single-origin bean profile every single morning. The sourdough morning bun was warm and flaky too!',
    createdAt: '2024-03-14T15:24:00Z',
    replyText: 'Thank you so much Marcus! We take serious pride in dialing in those daily tasting notes, so hearing this from a true coffee lover makes our day. Next time you stop by Hayes Valley, try our natural process Costa Rica! — Warmly, Elena & the Artisan Roast Barista Team ☕',
    repliedAt: '2024-03-14T16:40:00Z',
    replySource: 'ai',
    sentiment: 'positive',
  },
  {
    id: 'rev-2',
    gbpAccountId: 'gbp-artisan',
    reviewerName: 'Sarah Jenkins',
    reviewerPhotoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&q=80',
    rating: 5,
    text: 'A gorgeous bright café space with plenty of natural sunlight and fantastic music. Perfect spot for reading a novel or catching up with a friend over oat flat whites.',
    createdAt: '2024-03-13T11:10:00Z',
    replyText: undefined,
    sentiment: 'positive',
  },
  {
    id: 'rev-3',
    gbpAccountId: 'gbp-artisan',
    reviewerName: 'David K.',
    reviewerPhotoUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=100&q=80',
    rating: 2,
    text: 'Waited over 20 minutes for two iced lattes on a Tuesday morning. The cashier was polite, but drinks took way too long and one was made with whole milk instead of oat milk.',
    createdAt: '2024-03-12T09:45:00Z',
    replyText: undefined,
    sentiment: 'negative',
  },
  {
    id: 'rev-4',
    gbpAccountId: 'gbp-artisan',
    reviewerName: 'Chloe Dupond',
    reviewerPhotoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=100&q=80',
    rating: 4,
    text: 'Delicious cardamom pastry and top-notch espresso. Seating is a bit limited during peak weekend rush, so be prepared to wait a couple minutes for an outdoor bench.',
    createdAt: '2024-03-10T14:15:00Z',
    replyText: undefined,
    sentiment: 'positive',
  },
  {
    id: 'rev-5',
    gbpAccountId: 'gbp-artisan',
    reviewerName: 'Trevor Vance',
    reviewerPhotoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=100&q=80',
    rating: 1,
    text: 'Found a stray hair on the plate next to my avocado toast. Showed the cashier and got an eye roll before a replacement. Not coming back.',
    createdAt: '2024-03-08T12:00:00Z',
    replyText: undefined,
    sentiment: 'negative',
  },
  // Blue harbor review
  {
    id: 'rev-6',
    gbpAccountId: 'gbp-blueharbor',
    reviewerName: 'Aria Montgomery',
    reviewerPhotoUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=100&q=80',
    rating: 5,
    text: 'Incredible sunset view over Alcatraz and the Golden Gate bridge. The clam chowder bread bowl and cedar plank salmon were sublime.',
    createdAt: '2024-03-14T20:30:00Z',
    replyText: 'Dear Aria, thank you for sharing your experience! Watching the sunset over the bay with our steaming clam chowder is our favorite part of the evening. See you on the pier again soon! — Chef Mateo & The Pier 39 Crew 🐟',
    repliedAt: '2024-03-14T21:00:00Z',
    replySource: 'manual',
    sentiment: 'positive',
  },
];

export const INITIAL_PHOTOS: GbpPhoto[] = [
  {
    id: 'photo-1',
    gbpAccountId: 'gbp-artisan',
    category: 'LOGO',
    url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    caption: 'Official Artisan Roast & Bakery Emblem',
    uploadedAt: '2024-01-16T12:00:00Z',
    viewsCount: 15420,
    dimensions: '1080 x 1080',
  },
  {
    id: 'photo-2',
    gbpAccountId: 'gbp-artisan',
    category: 'COVER',
    url: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?auto=format&fit=crop&w=1200&q=80',
    caption: 'Morning sun streaming into the main Hayes St brew bar',
    uploadedAt: '2024-01-16T12:05:00Z',
    viewsCount: 38900,
    dimensions: '1920 x 1080',
  },
  {
    id: 'photo-3',
    gbpAccountId: 'gbp-artisan',
    category: 'INTERIOR',
    url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=800&q=80',
    caption: 'Communal walnut tables and plant-filled espresso nook',
    uploadedAt: '2024-02-01T14:10:00Z',
    viewsCount: 8450,
    dimensions: '1200 x 800',
  },
  {
    id: 'photo-4',
    gbpAccountId: 'gbp-artisan',
    category: 'EXTERIOR',
    url: 'https://images.unsplash.com/photo-1525610553991-2bede1a236e2?auto=format&fit=crop&w=800&q=80',
    caption: 'Storefront entrance on Hayes Street with outdoor parklet',
    uploadedAt: '2024-02-05T10:30:00Z',
    viewsCount: 12100,
    dimensions: '1200 x 800',
  },
  {
    id: 'photo-5',
    gbpAccountId: 'gbp-artisan',
    category: 'PRODUCT',
    url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80',
    caption: 'Velvety micro-foam flat white and buttery cardamom knot',
    uploadedAt: '2024-02-12T09:20:00Z',
    viewsCount: 9730,
    dimensions: '800 x 800',
  },
  {
    id: 'photo-6',
    gbpAccountId: 'gbp-artisan',
    category: 'TEAM',
    url: 'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?auto=format&fit=crop&w=800&q=80',
    caption: 'Barista team smiling during morning calibration',
    uploadedAt: '2024-02-15T15:00:00Z',
    viewsCount: 6420,
    dimensions: '1200 x 800',
  },
  {
    id: 'photo-7',
    gbpAccountId: 'gbp-artisan',
    category: 'AT_WORK',
    url: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=800&q=80',
    caption: 'Pouring hot water in concentric circles for Kalita Wave',
    uploadedAt: '2024-02-20T11:45:00Z',
    viewsCount: 5200,
    dimensions: '1200 x 800',
  },
];

export const INITIAL_PRICING_PLANS: PricingPlan[] = [
  {
    id: 'plan-single',
    name: 'Single Business',
    priceMonthly: 29,
    maxGbpAccounts: 1,
    features: [
      '1 Google Business Profile',
      'AI-Assisted Review Replies (Claude/GPT)',
      'Post Scheduling & Calendar',
      'Basic Insights & KPI Dashboard',
      'Photo & Media Manager',
      'Standard Email Support',
    ],
    isAgencyPlan: false,
    version: 2,
    activeSubscribers: 1420,
  },
  {
    id: 'plan-agency-starter',
    name: 'Agency Starter',
    priceMonthly: 99,
    maxGbpAccounts: 5,
    features: [
      'Up to 5 Client GBP Accounts',
      'Full Multi-Client Switcher',
      'AI Auto-Reply with Custom Guardrails',
      'Multi-Location Bulk Post Scheduling',
      'Consolidated + Per-Client Reporting',
      '3 Team Member Seats',
      'Client Comparison Analytics',
    ],
    isAgencyPlan: true,
    version: 1,
    activeSubscribers: 310,
  },
  {
    id: 'plan-agency-pro',
    name: 'Agency Pro',
    priceMonthly: 199,
    maxGbpAccounts: 15,
    features: [
      'Up to 15 Client GBP Accounts',
      'White-Label PDF Reports (Upcoming)',
      'Custom LLM API Key (Bring Your Own)',
      'Unlimited Post Scheduling',
      'Automated Review Auto-Replies (24/7)',
      '10 Team Member Seats',
      'Priority Live Chat & SLA Support',
    ],
    isAgencyPlan: true,
    version: 3,
    activeSubscribers: 185,
  },
  {
    id: 'plan-enterprise',
    name: 'Enterprise / Scale',
    priceMonthly: 499,
    maxGbpAccounts: 50,
    features: [
      '50+ Client GBP Accounts',
      'Dedicated Account Manager',
      'Custom SLA & SOC2 Compliance',
      'Unlimited Team Seats',
      'Custom Webhooks & REST API Access',
      'Tailored Onboarding Assistance',
    ],
    isAgencyPlan: true,
    version: 1,
    activeSubscribers: 42,
  },
];

export const INITIAL_TEAM_MEMBERS: AgencyTeamMember[] = [
  {
    id: 'team-1',
    agencyId: 'user-agency',
    name: 'Marcus Vance',
    email: 'marcus@peakscalemedia.com',
    role: 'admin',
    assignedClientIds: [],
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    invitedAt: '2023-11-10T10:30:00Z',
    status: 'active',
  },
  {
    id: 'team-2',
    agencyId: 'user-agency',
    name: 'Jessica Reynolds',
    email: 'jessica@peakscalemedia.com',
    role: 'manager',
    assignedClientIds: ['gbp-blueharbor', 'gbp-bellavita'],
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    invitedAt: '2023-12-05T09:00:00Z',
    status: 'active',
  },
  {
    id: 'team-3',
    agencyId: 'user-agency',
    name: 'Devon Miller',
    email: 'devon@peakscalemedia.com',
    role: 'contributor',
    assignedClientIds: ['gbp-summitdental', 'gbp-apexfitness'],
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    invitedAt: '2024-01-10T14:20:00Z',
    status: 'active',
  },
];

export const INITIAL_GLOBAL_SETTINGS: GlobalPlatformSettings = {
  defaultLlmProvider: 'anthropic',
  defaultModel: 'claude-3-5-sonnet',
  maintenanceMode: false,
  globalAnnouncement: 'Welcome to Partner.ai v2.4! Google Business Profile OAuth 2.0 sync speeds are now 4x faster.',
  systemPromptPreset: 'You are an empathetic, concise, and brand-aligned Google Business Profile reputation manager. Always prioritize building trust, resolving issues quickly, and thanking happy customers.',
  apiRateLimitPerMin: 120,
  gbpSyncIntervalMinutes: 30,
};

export const MOCK_TIMESERIES = [
  { date: 'Mon', views: 420, searches: 310, calls: 24, directions: 45, clicks: 38 },
  { date: 'Tue', views: 510, searches: 380, calls: 32, directions: 56, clicks: 42 },
  { date: 'Wed', views: 490, searches: 360, calls: 28, directions: 51, clicks: 47 },
  { date: 'Thu', views: 630, searches: 490, calls: 41, directions: 68, clicks: 59 },
  { date: 'Fri', views: 820, searches: 640, calls: 58, directions: 94, clicks: 82 },
  { date: 'Sat', views: 980, searches: 790, calls: 74, directions: 125, clicks: 104 },
  { date: 'Sun', views: 760, searches: 580, calls: 46, directions: 88, clicks: 76 },
];

export const MOCK_TIMESERIES_30D = [
  { date: 'Wk 1', views: 3420, searches: 2450, calls: 180, directions: 380, clicks: 290 },
  { date: 'Wk 2', views: 4120, searches: 3100, calls: 220, directions: 440, clicks: 350 },
  { date: 'Wk 3', views: 3950, searches: 2980, calls: 195, directions: 415, clicks: 320 },
  { date: 'Wk 4', views: 4890, searches: 3820, calls: 265, directions: 520, clicks: 440 },
];
